/*
 * generated by Xtext
 */
package org.xtext.example.mydsl;

import org.eclipse.xtext.linking.ILinker;
import org.eclipse.xtext.linking.ILinkingService;
import org.eclipse.xtext.naming.IQualifiedNameConverter;
import org.eclipse.xtext.naming.IQualifiedNameProvider;
import org.xtext.example.mydsl.scoping.MyDslLazyLinker;
import org.xtext.example.mydsl.scoping.MyDslLinkingService;
import org.xtext.example.mydsl.scoping.MyDslNameProvider;
import org.xtext.example.mydsl.scoping.MyDslQualifiedNameConverter;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class MyDslRuntimeModule extends org.xtext.example.mydsl.AbstractMyDslRuntimeModule {

	@Override
	public Class<? extends IQualifiedNameProvider> bindIQualifiedNameProvider() {
		return MyDslNameProvider.class;
	}
	
	@Override
	public Class<? extends ILinker> bindILinker() {
		return MyDslLazyLinker.class;
	}
	
	@Override
	public Class<? extends ILinkingService> bindILinkingService() {
		return MyDslLinkingService.class;
	}

	public Class<? extends IQualifiedNameConverter> bindNameConverter() {
		return MyDslQualifiedNameConverter.class;
	}

}
